version: '3'
services:

  bank:
    container_name: bank
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bank-db:5432/bank
    ports:
      - "8080:8080"
    depends_on:
      - bank-db

  bank-db:
    container_name: bank-db
    image: postgres:16
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
