version: '3'
services:

  abn-amro:
    container_name: abn-amro
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://abn-amro-db:5432/abnamro
    ports:
      - "8080:8080"
    depends_on:
      - abn-amro-db

  abn-amro-db:
    container_name: abn-amro-db
    image: postgres:16
    environment:
      POSTGRES_USER: abn-amro
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: abnamro
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
